os: linux
dist: xenial

language: python

jobs:
  include:
    # Python version is just for the look on travis.
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.7
      env: TOXENV=py37-django111
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.7
      env: TOXENV=py37-django20
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.7
      env: TOXENV=py37-django21
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.8
      env: TOXENV=py38-django22
    - python: 3.9
      env: TOXENV=py39-django22
    - python: 3.6
      env: TOXENV=py36-django30
    - python: 3.7
      env: TOXENV=py37-django30
    - python: 3.8
      env: TOXENV=py38-django30
    - python: 3.9
      env: TOXENV=py39-django30
    - python: 3.6
      env: TOXENV=py36-django31
    - python: 3.7
      env: TOXENV=py37-django31
    - python: 3.8
      env: TOXENV=py38-django31
    - python: 3.9
      env: TOXENV=py39-django31
    - python: 3.6
      env: TOXENV=py36-flake8
    - python: 3.6
      env: TOXENV=py36-django111-coverage
    - python: 3.6
      env: TOXENV=py36-django111-postgresql

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database dirtyfields_test;' -U postgres

script:
  - tox

install:
  - pip install tox
  - pip install coveralls
  - pip install -e .

after_success:
  - if test "$TOXENV" = "py36-django111-coverage"; then coveralls; fi

deploy:
  edge: true  # opt in to dpl v2
  provider: pypi
  # We use the __token__ special key to indicate that we use Pypi API token, instead of the
  # username/password combinaison
  username: "__token__"
  # No need to provide the password anymore. It has been set as an PYPI_PASSWORD environment variable
  # on travis-ci.org web interface, and is picked automatically in this deploy stage for pypi.
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
    all_branches: true
    repo: romgar/django-dirtyfields
